

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({
  subsets: ["latin"], // You can also add 'latin-ext' or other subsets if needed
  weight: ["400", "500", "700"], // Specify the font weights you want to use
  style: ["normal", "italic"], // Optionally, add italic if needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <UserProvider>
        <body className={inter.className}>
          {children}
        </body>
      </UserProvider>

    </html>
  );
}
